### ISSUE TITLE
Cleanup Before First Release

### ISSUE THREAD

**Issue by nrayburn-tech** [oxc-project/oxc-intellij-plugin#54]
- [x] Update the pluginGroup in [gradle.properties](https://github.com/oxc-project/oxc-intellij-plugin/blob/main/gradle.properties), the plugin id in [plugin.xml](https://github.com/oxc-project/oxc-intellij-plugin/blob/main/src/main/resources/META-INF/plugin.xml), and the kotlin packages
- [x] Add a plugin icon to [plugin.xml](https://github.com/oxc-project/oxc-intellij-plugin/blob/main/src/main/resources/META-INF/plugin.xml) #68
- [x] Update the vendor in [plugin.xml](https://github.com/oxc-project/oxc-intellij-plugin/blob/main/src/main/resources/META-INF/plugin.xml) #69
- [x] Cleanup the [README.md](https://github.com/oxc-project/oxc-intellij-plugin/blob/main/README.md) #70
- [x] Update Github secrets with the required tokens to publish
  - [x] Set the [Plugin Signing](https://plugins.jetbrains.com/docs/intellij/plugin-signing.html?from=IJPluginTemplate) related [secrets](https://github.com/JetBrains/intellij-platform-plugin-template#environment-variables)
  - [x] Set the [Deployment Token](https://plugins.jetbrains.com/docs/marketplace/plugin-upload.html?from=IJPluginTemplate)
- [x] Remove original template code that isn't used by the plugin https://github.com/oxc-project/oxc-intellij-plugin/pull/56
- [x] Update changelog #79
- [x] Review the [Legal Agreements](https://plugins.jetbrains.com/docs/marketplace/legal-agreements.html?from=IJPluginTemplate).
- [x] Config file support https://github.com/oxc-project/oxc-intellij-plugin/issues/84.
- [x] Update plugin icon to be 40px x 40px. https://github.com/oxc-project/oxc-intellij-plugin/blob/main/src/main/resources/META-INF/pluginIcon.svg (Possibly https://github.com/oxc-project/oxc-intellij-plugin/blob/main/src/main/resources/icons/oxlint_round.svg as well)
- [x] Update the vendor with an appropriate `email` attribute. https://github.com/oxc-project/oxc-intellij-plugin/blob/main/src/main/resources/META-INF/plugin.xml#L5.
- [x] Configure a license in GitHub.

Last step is to [Publish a plugin manually](https://plugins.jetbrains.com/docs/intellij/publishing-plugin.html?from=IJPluginTemplate) for the first time.

**Comment by nrayburn-tech** [comment]
@IWANABETHATGUY I think you or somebody else on the project will need to handle the Github secrets, review the legal agreement (I think this is just an FYI, no action is required), and once everything else is done publishing the plugin manually.

**Comment by IWANABETHATGUY** [comment]
> You might want to pick a better ID here (and don't forget to change the URL), given that this repository is now placed under @oxc-project:
> 
> ```ini
> pluginGroup = com.github.iwanabethatguy.oxcintellijplugin
> pluginName = oxc-intellij-plugin
> pluginRepositoryUrl = https://github.com/IWANABETHATGUY/oxc-intellij-plugin
> ```
> 
> `pluginGroup` is the ID used to uniquely identify a plugin, whereas `pluginName` is the user-facing name. The latter should be in Title Case and does not contain `intellij` (or `jetbrains`, `webstorm`, etc.). More information can be found in [this guide](https://plugins.jetbrains.com/docs/marketplace/best-practices-for-listing.html).

Yeah, we already discuss here https://github.com/oxc-project/oxc-intellij-plugin/pull/66#issuecomment-2408798000

**Comment by nrayburn-tech** [comment]
Anything else to include in a first release?  Working on the changelog updates now.  I'll keep working on features when I can, but I wasn't sure if there was anything else necessary for a first release.

**Comment by IWANABETHATGUY** [comment]
I think it looks good for now, let me add a secret and try to make the release workflow work

**Comment by IWANABETHATGUY** [comment]
Thanks for your work again

**Comment by nrayburn-tech** [comment]
I think you have to do a manual release for the first one.  It looks like there might be some manual parts involved [Publish a plugin manually](https://plugins.jetbrains.com/docs/intellij/publishing-plugin.html?from=IJPluginTemplate).

**Comment by nrayburn-tech** [comment]
Should probably implement https://github.com/oxc-project/oxc-intellij-plugin/issues/84 before a release, but other than that I’m not aware of any blockers for a first release.

**Comment by IWANABETHATGUY** [comment]
> Should probably implement #84 before a release, but other than that I’m not aware of any blockers for a first release.

Ok, let's wait for the nested configuration to land and then push forward.

**Comment by simonbuchan** [comment]
I just went through the process for a manual plugin release (having missed this, dammit) - you can specify a channel like `preview` so it doesn't get marked as a stable release and, as far as I can tell, not recommended in the plugins search.

The page is here, still under moderation review, so let me know if it shows up and confuses people and I'll take it down or whatever: https://plugins.jetbrains.com/plugin/25948-oxlint

**Comment by rakleed** [comment]
@simonbuchan 

![CleanShot 2024-12-12 at 11 56 36](https://github.com/user-attachments/assets/f88269b7-c48c-4e86-9d75-e8475a181b28)

**Comment by zubhav** [comment]
@IWANABETHATGUY Just an update here - nested configs are now available in Oxlint - https://oxc.rs/docs/guide/usage/linter/nested-config.html

**Comment by Boshen** [comment]
@nrayburn-tech 

https://plugins.jetbrains.com/plugin/27061-oxc 

Probably not visible to public, here's the screeshot :

<img width="1236" alt="Image" src="https://github.com/user-attachments/assets/70e51855-dc79-46d4-814f-4b143d9d5687" />

5 minutes later ...

<img width="1426" alt="Image" src="https://github.com/user-attachments/assets/0f32f310-2e1c-47e1-be59-aef04a2e80bc" />

What I did:

* Downloaded the build artifact from https://github.com/oxc-project/oxc-intellij-plugin/actions/runs/14438821950
* Uploaded the `oxc-intellij-plugin-0.0.1.jar`

<img width="706" alt="Image" src="https://github.com/user-attachments/assets/a3c7e5e1-3df9-4a97-8305-0a6ceb3adc1b" />

* Followed https://plugins.jetbrains.com/docs/intellij/plugin-signing.html and added

<img width="768" alt="Image" src="https://github.com/user-attachments/assets/6032a49e-5274-45fa-9538-f7b9f360f403" />

---

What I didn't do: provide secrets to IDE, I don't want to install any of the relevant tools 😓 : https://plugins.jetbrains.com/docs/intellij/plugin-signing.html#provide-secrets-to-ide

Please find me on discord or x with your contact info, and I'll send you the secrets. I *really* don't want to sign it locally.

**Comment by nrayburn-tech** [comment]
I don't think the plugin has to be signed, it's just preferred. So, if the first manual version isn't signed we can publish the subsequent versions through GitHub actions and those should be signed.

I don't see anything wrong with what you did. I think we just wait a few days for JetBrains to get back to us with their review.

Over the next few days, I'll try to get the documentation together for releasing with GitHub actions. Right now, it should be the same as described here https://github.com/JetBrains/intellij-platform-plugin-template?tab=readme-ov-file#continuous-integration.

**Comment by nrayburn-tech** [comment]
Looks like this has been approved by JetBrains. I think all that needs to be done here is to publish the release in GitHub. It should create a PR with the changelog update after you publish the release.

https://github.com/oxc-project/oxc-intellij-plugin/releases/tag/untagged-54fab6df06e0fb30961e

It looks like I have access to publish the release, but I wasn't sure if that was intentional so I didn't want to just do it.

**Comment by Boshen** [comment]
> Looks like this has been approved by JetBrains. I think all that needs to be done here is to publish the release in GitHub. It should create a PR with the changelog update after you publish the release.
> 
> https://github.com/oxc-project/oxc-intellij-plugin/releases/tag/untagged-54fab6df06e0fb30961e
> 
> It looks like I have access to publish the release, but I wasn't sure if that was intentional so I didn't want to just do it.

![Image](https://github.com/user-attachments/assets/7a54642d-4f8b-4450-890d-a3f84845ac5c)

Build works! 

> Failed to upload plugin: Upload failed: The com.github.oxc.project.oxcintellijplugin plugin already contains version 0.0.1 in channel 

Would you like to do some clean ups and release v0.0.2?

**Comment by nrayburn-tech** [comment]
Thanks! Yes, I’m going to fix an issue that has already been reported with the icon size change. Once I get that done, I’ll go through the release steps for the automated releases and get it documented.
