### ISSUE TITLE
Feature Roadmap

### ISSUE THREAD

**Issue by nrayburn-tech** [oxc-project/oxc-intellij-plugin#55]
I've been trying to get the IntelliJ plugin updated with the same features that the VS Code plugin has.  It shouldn't take too long to get there.

What other features should be looked into?
Does the VS Code plugin have a roadmap somewhere?
Could we start a feature list somewhere (either here or somewhere else)?

- [x] Custom icons for config files. #61
- [x] Configuration of the run mode for OnType and OnSave #62
- [x] Watching configuration files for changes and either restarting or updating the LSP that the config has changed #63
- [x] Configuration option to use a specific LSP file path instead of searching the workspace for it. #64
- [x] Associate custom JSON schema with config files. #65
- [x] Configurable debug logging #78

**Comment by nrayburn-tech** [comment]
Found https://github.com/oxc-project/oxc/issues/2719#issuecomment-2076695221 about the VS Code extension indicating there is room for improvement on the VS Code side as well.

**Comment by nrayburn-tech** [comment]
- [ ] Custom icons for config files.
     - Should we change the icon for eslint config files too, or only oxlint config files?  Or something more complex like if oxc is in the workspace, override eslint otherwise leave it as is?
- [ ] Configuration of the run mode for OnType and OnSave
- [ ] Watching configuration files for changes and either restarting or updating the LSP that the config has changed
- [ ] Configuration option to use a specific LSP file path instead of searching the workspace for it.
- [ ] Associate custom JSON schema with config files.
- [ ] Configurable debug logging

**Comment by Sysix** [comment]
are their any plans to support other jetbrains IDE too? 
I am missing the PHPStorm / Webstorm support :)

**Comment by nrayburn-tech** [comment]
I don’t think a version has been released yet, but it should work with any JetBrains IDE that has the JavaScript plugin installed. This should be available in all paid versions of the IDE. I’m not sure about the unpaid versions.

**Comment by nrayburn-tech** [comment]
Closing this as the original list of targeted features have been completed here. New issues will be created for other features.
